# Welcome to Jekyll!
#

# Site settings
title: Flint and Charlie
description: |
  A Galactic Pickle
owner: Kirikoro Studios # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: pontus.lindgren@kirikoro.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://flintandcharlie.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/happypwn
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/kirikorostudios
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
